#spring.application.name=service-order
#server.port=8000
#
#spring.cloud.nacos.server-addr=127.0.0.1:8848
#spring.cloud.nacos.config.import-check.enabled=false
##logging.level.com.ytung.order.feign:debug
#
#spring.profiles.include=feign